server:
  port: ${port:8080}

spring:
  application:
    name: nisum-person
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    url: "jdbc:h2:mem:reba;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

app:
  properties:
   password-pattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$

  jwt:
    secret: secretKey

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR
